// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWmnxetiLq87C9qwFoNsbSy1HB2fBTJ2w',
    authDomain: 'salonapp1-819db.firebaseapp.com',
    databaseURL: 'https://salonapp1-819db-default-rtdb.firebaseio.com',
    projectId: 'salonapp1-819db',
    storageBucket: 'salonapp1-819db.appspot.com',
    messagingSenderId: '1023442335589',
    appId: '1:1023442335589:web:25c04a321dab0e02d3938c',
    measurementId: 'G-EKCHV4GSNP'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8V4VqGax4XZM4NTqZiFfTBf7koDJUyG0',
    appId: '1:1023442335589:android:27a240ccc9f5b9ead3938c',
    messagingSenderId: '1023442335589',
    projectId: 'salonapp1-819db',
    storageBucket: 'salonapp1-819db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4w-VpkFZnOqbene72nNtkNmk7eq-Njg',
    appId: '1:1023442335589:ios:c32bff69b010a4a5d3938c',
    messagingSenderId: '1023442335589',
    projectId: 'salonapp1-819db',
    storageBucket: 'salonapp1-819db.appspot.com',
    iosBundleId: 'com.example.salonapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4w-VpkFZnOqbene72nNtkNmk7eq-Njg',
    appId: '1:1023442335589:ios:739caf6afb1a3f43d3938c',
    messagingSenderId: '1023442335589',
    projectId: 'salonapp1-819db',
    storageBucket: 'salonapp1-819db.appspot.com',
    iosBundleId: 'com.example.salonapp1.RunnerTests',
  );
}
